### ISSUE TITLE
Recent Spigot update. EHM console spam

### ISSUE THREAD

**Issue by LigerXT5** [MLG-Fortress/ExtraHardMode#25] opened 2016-03-10 00:22 UTC
After restarting the server, upon first player entering, the errors appear.

`[17:16:08] [Server thread/WARN]: [ExtraHardMode] Task #182 for ExtraHardMode v3.7.1 generated an exception
java.lang.NullPointerException
	at com.extrahardmode.module.PlayerModule.getArmorPoints(PlayerModule.java:227) ~[?:?]
	at com.extrahardmode.task.ArmorWeightTask.run(ArmorWeightTask.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-3104eb1-daf4514]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-3104eb1-daf4514]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [Spigot.jar:git-Spigot-3104eb1-daf4514]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-3104eb1-daf4514]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot.jar:git-Spigot-3104eb1-daf4514]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot.jar:git-Spigot-3104eb1-daf4514]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

**Comment by RoboMWM** [comment] 2016-03-10 00:28
Duplicate of #21

**Closed by RoboMWM** 2016-03-10 00:28 UTC
