### ISSUE TITLE
NPE, cause unknown

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#101] opened 2017-07-21 01:03 UTC
Spigot 1.12
EHM 3.12

No idea what caused this, found in log after the fact. Only one player on test server.

```
[18:00:03 ERROR]: Could not pass event PrepareItemCraftEvent to ExtraHardMode v3.12
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:772) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.Container.a(Container.java:652) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.ContainerPlayer.a(ContainerPlayer.java:75) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.InventoryCrafting.setItem(InventoryCrafting.java:130) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:83) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at co.kepler.fastcraftplus.recipes.CraftingListener$1.run(CraftingListener.java:60) [FastCraftPlus-0.27.2.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.extrahardmode.features.MoreTnt.beforeCraft(MoreTnt.java:67) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar-2017-07-20-1513:git-Spigot-99c2a37-9a82fa7]
        ... 16 more
```

**Comment by RoboMWM** [comment] 2017-07-21 02:49
Use 3 tildes `\`\`\`` to denote a code block. Also, update to 3.12.1 (which was released hours after 3.12, hence no spigot update)

**Comment by RoboMWM** [comment] 2017-07-21 02:53
Duplicate of #92

**Comment by RoboMWM** [comment] 2017-07-21 02:54
Oh, you're the author of that issue too lol

**Comment by SlimeDog** [comment] 2017-07-21 02:58
Spigot forums do not prevent subsequent (different) uploads. But I'll follow on Bukkit now. :(

**Closed** 2017-07-21 03:01 UTC
Labels: duplicate

**Comment by RoboMWM** [comment] 2017-07-21 18:44
@SlimeDog the link on spigot is an external link to the 3.12.1 release.
