### ISSUE TITLE
ExtraHardMode newest Spigot release, Error still persists:

### ISSUE THREAD

**Issue by Shlobdon** [MLG-Fortress/ExtraHardMode#97] opened 2017-06-18 17:47 UTC
This error is still being put into console:
```18.06 13:51:06 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
18.06 13:51:06 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
18.06 13:51:06 [Server] INFO at sun.reflect.GeneratedMethodAccessor1095.invoke(Unknown Source) ~[?:?]
18.06 13:51:06 [Server] INFO at com.extrahardmode.features.MoreTnt.beforeCraft(MoreTnt.java:67) ~[?:?]
18.06 13:51:06 [Server] INFO Caused by: java.lang.NullPointerException
18.06 13:51:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
18.06 13:51:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1885) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.Container.a(Container.java:251) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.ContainerPlayer.b(ContainerPlayer.java:146) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.SlotResult.a(SourceFile:72) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.InventoryCrafting.splitStack(InventoryCrafting.java:122) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.ContainerPlayer.a(ContainerPlayer.java:75) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at net.minecraft.server.v1_12_R1.Container.a(Container.java:652) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:770) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-cd6ba67-732911e]
18.06 13:51:06 [Server] INFO org.bukkit.event.EventException: null
18.06 13:51:06 [Server] ERROR Could not pass event PrepareItemCraftEvent to ExtraHardMode v3.12`

**Comment by Shlobdon** [comment] 2017-06-18 17:50
18.06 13:51:06 [Server] INFO at com.extrahardmode.features.MoreTnt.beforeCraft(MoreTnt.java:67) ~[?:?]  
Should be somewhere in there.


Edit: I checked that stop in your GitHub b/c I was going to tell you the fix, but it seems as if MoreInt.java has been update since..


Maybe your download link on forums isn't the correct link to the newest jar?

**Comment by RoboMWM** [comment] 2017-06-19 02:19
Um, next time paste from logs/latest.log instead of multijunk's backwards console. Also, please post in the same issue 

Duplicate of #92

**Closed by RoboMWM** 2017-06-19 02:19 UTC
