### ISSUE TITLE
Being injured by standing on a stone that is softened

### ISSUE THREAD

**Issue by manmadehuman** [MLG-Fortress/ExtraHardMode#99] opened 2017-06-28 14:43 UTC
When standing next to ore, the player will be injured by the stone they are standing on and then get nausea, even though that stone doesn't fall.  I think this is the number 1 complaint we have.

**Comment by RoboMWM** [comment] 2017-06-28 17:37
Technically the stone does fall. Duplicate of #23

**Closed by RoboMWM** 2017-06-28 17:37 UTC

**Comment by RoboMWM** [comment] 2018-11-07 22:36
Solved, see #23
