### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by cephalopoid** [MLG-Fortress/ExtraHardMode#321] opened 2023-08-21 15:07 UTC
The plugin does not allow you to translate messages into Russian. After plugin restart, hieroglyphs appear in the config.
I tried to convert messages through the site (http://0xcc.net/jsescape/), but it did not give any results.
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/78875375-12ab-44c5-b68a-06091888efaa)
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/8e55f842-6f69-40fc-8335-b485f537fdec)
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/77957b32-546d-4462-96b7-a1e3927d9221)
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/0fcbf35e-0c7e-4416-8782-ce7438731ed6)

**Comment by cephalopoid** [comment] 2023-08-21 15:08
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/cebdadb3-4d00-4997-b742-ad313a8ff7d9)
![image](https://github.com/MLG-Fortress/ExtraHardMode/assets/62611545/986eda87-0969-4bed-9c62-ad66e3d6720f)

**Comment by RoboMWM** [comment] 2023-08-24 17:27
I think there's a flag you need to set in your server to make it run with utf-8 encoding if you're using windows iirc.

**Comment by RoboMWM** [comment] 2023-08-24 17:28
https://github.com/MLG-Fortress/ExtraHardMode/issues/245

**Comment by RoboMWM** [comment] 2023-08-24 17:28
duplicate of #245

**Closed by RoboMWM** 2023-08-24 17:28 UTC
