### ISSUE TITLE
Suggestions Hunting

### ISSUE THREAD

**Issue by towncraftserver** [MLG-Fortress/ExtraHardMode#84] opened 2017-05-03 01:27 UTC
Hey, 
I saw robo post this about a year ago, and I wanted to re-instate this! 
I think it would be amazing!

So to sum up, give sheep/cows/pigs/chickens the same AI as cats/rabbits, 
Where they RUN when you are near them! 

Suggestions:
-Animals run when you are close, making hunting harder.
-Disable luring them in with carrots/wheat/seeds (as of now, if you hold a carrot in your hand, you can OH SO EASILY hunt rabbits - kinda stupid)
-Only being able to capture them with leads
-Maybe something like ONCE you have used a lead on a sheep/cow/pig/chicken it would then be tame? So if you were to farm them they wouldn't always be running around like stupid rabbits in a pen!

I want this so freakin bad! When I first read the post about it, I got really giddy and excited!
PLEASE make this happen

**Comment by RoboMWM** [comment] 2017-05-04 02:49
Um, isn't this a duplicate of #9

**Comment by towncraftserver** [comment] 2017-05-04 03:01
No.  9 is about animals in a small area, being too close to each other and taking damage. 

I was referring to animals in the wild 
So for example, you're roaming the lands and see a sheep.  You go to kill it.  But rather than it just standing there it would run away similar to how rabbits and ocelots act when you're close.

**Comment by RoboMWM** [comment] 2017-05-04 15:19
Ok, then #10 and just append whatever ideas there (if you haven't already).

**Closed by RoboMWM** 2017-05-04 15:19 UTC
Labels: duplicate
