### ISSUE TITLE
Prefix configuration

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#133] opened 2018-10-22 00:49 UTC
Spigot 1.13.1 latest
EHM 3.13.alpha.2

Please support configuration of the in-game message prefix. Presently it is set to the equivalent of
> &c[EHM] &r

**Comment by RoboMWM** [comment] 2018-11-09 05:50
Duplicate of #51

**Closed** 2018-11-09 05:51 UTC
