### ISSUE TITLE
after translate message.yml, all Garbled

### ISSUE THREAD

**Issue by lammaHK** [MLG-Fortress/ExtraHardMode#268] opened 2021-01-14 22:04 UTC
I change the msg and I reloaded it. It becomes 

Before:
Scoreboard Title: [ExtraHardMode]
After:
Scoreboard Title: ÃƒÆ’Ã‚Â¦Ãƒâ€šÃ‚Â¥Ãƒâ€šÃ‚ÂµÃƒÆ’Ã‚Â 

  StoneMiningHelp:
    Mode: notification
    Msg: You'll need an iron or diamond pickaxe to break stone.  Try exploring natural
      formations for exposed ore like coal, which softens stone around it when broken.

  StoneMiningHelp:
    Mode: notification
    Msg: ÃƒÆ’Ã‚Â§ÃƒÂ¯Ã‚Â¿Ã‚Â½Ãƒâ€šÃ‚Â«ÃƒÆ’Ã‚Â¦Ãƒâ€¦Ã‚Â Ãƒâ€¦Ã‚Â ÃƒÆ’Ã‚Â¦ÃƒÂ¯Ã‚Â¿Ã‚Â½ÃƒÂ¢Ã¢â€šÂ¬Ã¢

how can I fix it?

**Comment by RoboMWM** [comment] 2021-01-15 17:49
duplicate of #245

**Comment by RoboMWM** [comment] 2021-01-15 17:50
Oh actually, in this

**Closed** 2021-01-15 17:51 UTC

**Comment by lammaHK** [comment] 2021-01-16 21:37
still can't

**Comment by RoboMWM** [comment] 2021-01-17 00:52
ok, then I guess you've got other things, do the thing I mentioned in #245

**Comment by RoboMWM** [comment] 2021-01-17 00:53
Oh, you translated other stuff, not just that one example. Yea, def a duplicate of #245 then

**Comment by lammaHK** [comment] 2021-01-17 05:46
sorry,
where should I write for the start script, I saw but I dont know what -Dfile.encoding=UTF-8 place for where
